# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 20:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0003_auto_20180612_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='upvotes',
        ),
        migrations.AddField(
            model_name='course',
            name='upvotes',
            field=models.ManyToManyField(blank=True, related_name='course_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
