# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-15 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
